package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"btp_tokens/graph/model"
	"btp_tokens/internal/wallets"
	"context"
	"errors"
	"fmt"

	"github.com/shopspring/decimal"
)

// Transfer is the resolver for the transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, input model.Transfer) (string, error) {
	amount, err := decimal.NewFromString(input.Amount)
	if err != nil{
		return "", fmt.Errorf("Invalid amount format: %w", err)

	}

	if amount.IsNegative() || amount.IsZero() {
		return "", errors.New("Amount must be positive")
	}

	updatedBalance, err := r.WalletsService.Transfer(ctx, input.FromAddress, input.ToAddress, amount)
	if err != nil {
		if errors.Is(err, wallets.ErrorInsufficientBalance) {
			return "", errors.New("Insufficient balance")
		}
		return "", fmt.Errorf("Tranfer fail: %w", err)
	}

	return updatedBalance.String(), nil
}

// Empty is the resolver for the _empty field.
func (r *queryResolver) Empty(ctx context.Context) (*string, error) {
	// panic(fmt.Errorf("not implemented: Empty - _empty"))
	msg := "empty"
    return &msg, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
