package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"btp_tokens/graph/model"
	"btp_tokens/internal/wallets"
	"context"
	"errors"
	"fmt"

	"github.com/shopspring/decimal"
)

// Transfer is the resolver for the transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, input model.Transfer) (string, error) {
	amount := decimal.Decimal(input.Amount)

	if amount.IsNegative() || amount.IsZero() {
		return "", errors.New("amount must be positive")
	}

	if !amount.Equal(amount.Truncate(0)) {
		return "", errors.New("amount must be an integer (cant be floating point)")
	}

	updatedBalance, err := r.WalletsService.Transfer(ctx, input.FromAddress, input.ToAddress, amount)
	if err != nil {
		if errors.Is(err, wallets.ErrorInsufficientBalance) {
			return "", errors.New("insufficient balance")
		}
		return "", fmt.Errorf("transfer fail: %w", err)
	}

	return updatedBalance.String(), nil
}

// Empty is the resolver for the _empty field.
func (r *queryResolver) Empty(ctx context.Context) (*string, error) {
	// panic(fmt.Errorf("not implemented: Empty - _empty"))
	msg := "empty"
	return &msg, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
